---
title: "CEO Departures"
date: "`r Sys.Date()`"
author: "@elidomx"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Load Libraries and Data
```{r}
library(tidyverse)
library(janitor)
library(cowplot)
library(extrafont)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 18)

ceo <- tuesdata$departures

glimpse(ceo)

ceo %>% 
  filter(departure_code %in% c(3,4)) %>%
  count(fyear) %>%
  ggplot(aes(x = fyear, y = n)) +
  geom_line()


ceo %>% 
  filter(departure_code %in% c(3,4,5),
         fyear >= 2000 & fyear != 2019) %>% 
  mutate(departure_code = factor(ifelse(departure_code %in% c(3,4), "Involuntary", "Voluntary"))) %>% 
  count(fyear, departure_code) %>%
  ggplot(aes(x = fyear, y = n, color = departure_code)) +
  geom_line()

```

