# TidyTuesday 33: Avatar

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# devtools::install_github("averyrobbins1/appa")
# devtools::install_github("Ryo-N7/tvthemes")


library(tidyverse) # all the things
library(tidytext) # text analysis using tidy principles
library(tidytuesdayR)
library(tvthemes)
library(extrafont)
library(cowplot)
loadfonts()
pdfFonts()
```

```{r Wrangle}

dat <- appa::appa

glimpse(dat)
```

#### Here I'm basically copying Avery Robbin's code:

```{r}
data("stop_words")

dat_tidy <- dat %>% 
  select(book, chapter, chapter_num, character,
         character_words, imdb_rating) %>% 
  filter(character != "Scene Description") %>%
  group_by(book) %>% 
  mutate(line_num = row_number()) %>% 
  ungroup() %>% 
  unnest_tokens(word, character_words)

dat_tidy2 <- dat_tidy %>% 
  anti_join(stop_words)

dat_tidy2 %>%
  count(word, sort = TRUE) %>%
  slice(1:20) %>%
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = n, y = word)) +
  geom_col() +
  geom_text(aes(label = n), nudge_x = 12) +
  labs(title = "Most common words spoken in Avatar: The Last Airbender",
       x = "Count",
       y = "Words Spoken") +
  gghighlight(word %in% c("fire", "appa", "uncle"))

```

#### Here come my own simple visualizations
```{r}
dat_tidy2 %>% 
  filter(word %in% c("appa", "momo")) %>%
  group_by(book, chapter_num) %>%
  count(word) %>%
  ungroup() %>%
  ggplot(aes(chapter_num, n, fill = word)) +
  geom_col(position = "fill") +
  labs(title = "How many times were Appa and Momo called each chapter?") +
  facet_wrap(~ book) +
  scale_fill_avatar() +
  theme_theLastAirbender(title.font = "Slayer",
                         text.font = "Slayer",
                         title.size = 14) 
```

#### Better one:
```{r}
plot_1 <- dat_tidy2 %>% 
  filter(word %in% c("appa", "momo")) %>%
  group_by(book, chapter_num) %>%
  count(word) %>%
  ungroup() %>%
  ggplot(aes(chapter_num, n, color = word)) +
  geom_line(size = 2) +
  labs(title = "How many times were Appa and Momo called each chapter?", x = "Chapter", y = "# of times", subtitle = "Book:", caption = "#TidyTuesday | Data: {appa} | @elidom5") +
  scale_x_continuous(breaks = seq(0, 20, by = 10)) +
  facet_wrap(~ book) +
  scale_fill_avatar() +
  theme_theLastAirbender(title.font = "Slayer",
                         text.font = "Slayer",
                         title.size = 18) +
  theme(legend.title = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "right",
        plot.title = element_text(margin = margin(0, 0, 6, 0)),
        plot.caption = element_text(hjust = 1.12))
  
plot_grid(plot_1) +
  draw_image("pics/appa_2.png", scale = .45, x = 0.3, y = 0.17) +
  draw_image("pics/momo.png", scale = .38, x = -0.3, y = 0.13)



```

